name: GitPushTest
on: workflow_dispatch

jobs:
  push_test:
    name: Push Test
    runs-on: ubuntu-latest
    steps:
      - name: Make and Move Directory
        run: |
            today=$(date "+%Y%m%d-%H%M%S")
            dir_name="test_save"
            file_name="${test_save}/hogefile_${today}.txt"
            branch_name="hogebranch_${today}"
            git checkout -b $branch_name
            mkdir $dir_name
            touch $file_name
            git add "${dir_name}/*"
            git commit -m "GitPushTest"
            git push --set-upstream origin $branch_name